const players = [
  {
    id: 1,
    name: "Jason",
    avatar: "jsnAvatar.png",
    kills: 81,
    deaths: 52,
    assists: 48,
    wins: 4,
    looses: 5,
    winRate: ((4 / (4 + 5)) * 100).toFixed(1),
    profileLink: "https://op.gg/lol/summoners/euw/jsnuwu-69420",
    roundsPlayed: 9,
  },
  {
    id: 2,
    name: "David",
    avatar: "davidAvatar.png",
    kills: 78,
    deaths: 35,
    assists: 69,
    wins: 7,
    looses: 2,
    winRate: ((7 / (7 + 2)) * 100).toFixed(1),
    profileLink: "https://op.gg/lol/summoners/euw/gloriezzz-EUW",
    roundsPlayed: 9,
  },
  {
    id: 3,
    name: "Jenny",
    avatar: "jennyAvatar.png",
    kills: 30,
    deaths: 49,
    assists: 101,
    wins: 4,
    looses: 5,
    winRate: ((4 / (4 + 5)) * 100).toFixed(1),
    profileLink: "https://op.gg/lol/summoners/euw/M00NB0W-EUW",
    roundsPlayed: 9,
  },
  {
    id: 4,
    name: "Dennis",
    avatar: "DennisAvatar.png",
    kills: 64,
    deaths: 34,
    assists: 57,
    wins: 6,
    looses: 3,
    winRate: ((6 / (6 + 3)) * 100).toFixed(1),
    profileLink: "https://op.gg/lol/summoners/euw/Dhuscarr-2211",
    roundsPlayed: 9,
  },
  {
    id: 5,
    name: "Felix P",
    avatar: "felixPAvatar.png",
    kills: 67,
    deaths: 60,
    assists: 56,
    wins: 4,
    looses: 5,
    winRate: ((4 / (4 + 5)) * 100).toFixed(1),
    profileLink: "https://op.gg/lol/summoners/euw/2Luckyy-EUW",
    roundsPlayed: 9,
  },
  {
    id: 6,
    name: "Mechu",
    avatar: "MechuAvatar.png",
    kills: 4,
    deaths: 36,
    assists: 18,
    wins: 2,
    looses: 7,
    winRate: ((2 / (2 + 7)) * 100).toFixed(1),
    profileLink: "https://op.gg/lol/summoners/euw/Chuchiii-EUW",
    roundsPlayed: 9,
  },
  {
    id: 7,
    name: "Felix S",
    avatar: "felixSAvatar.png",
    kills: 12,
    deaths: 54,
    assists: 48,
    wins: 3,
    looses: 6,
    winRate: ((3 / (3 + 6)) * 100).toFixed(1),
    profileLink: "https://op.gg/lol/summoners/euw/ZeFX6-1173",
    roundsPlayed: 9,
  },
  {
    id: 8,
    name: "Mohammed",
    avatar: "MoAvatar.png",
    kills: 42,
    deaths: 42,
    assists: 53,
    wins: 3,
    looses: 6,
    winRate: ((3 / (3 + 6)) * 100).toFixed(1),
    profileLink: "https://op.gg/lol/summoners/euw/Killua%E3%83%84-SNIP1",
    roundsPlayed: 9,
  },
  {
    id: 9,
    name: "Nils",
    avatar: "NilsAvatar.png",
    kills: 38,
    deaths: 55,
    assists: 40,
    wins: 2,
    looses: 7,
    winRate: ((2 / (2 + 7)) * 100).toFixed(1),
    profileLink: "https://op.gg/lol/summoners/euw/Nols1000-0079",
    roundsPlayed: 9,
  },
  {
    id: 10,
    name: "Adrian",
    avatar: "AdrianAvatar.png",
    kills: 14,
    deaths: 26,
    assists: 7,
    wins: 5,
    looses: 4,
    winRate: ((5 / (5 + 4)) * 100).toFixed(1),
    profileLink: "https://op.gg/lol/summoners/euw/SuperAdi06-EUW",
    roundsPlayed: 9,
  },
  {
    id: 11,
    name: "Kristof",
    avatar: "KristofAvatar.png",
    kills: 29,
    deaths: 19,
    assists: 7,
    wins: 3,
    looses: 2,
    winRate: ((3 / (3 + 2)) * 100).toFixed(1),
    profileLink: "https://op.gg/lol/summoners/eune/FreeSummer-3225",
    roundsPlayed: 5,
  },
];

module.exports = players;